CREATE TABLE  "PROFESSOR" 
   (	"NRCONTRIBUINTE" NUMBER(9,0) NOT NULL ENABLE, 
	"NOMEPROPRIO" VARCHAR2(25) NOT NULL ENABLE, 
	"APELIDO" VARCHAR2(25) NOT NULL ENABLE, 
	"CATEGORIA" VARCHAR2(50) NOT NULL ENABLE, 
	"DATANASCIMENTO" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "PROFESSOR_PK" PRIMARY KEY ("NRCONTRIBUINTE") ENABLE
   ) ;

CREATE TABLE  "DEPARTAMENTO" 
   (	"NUMERO" NUMBER(3,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(50) NOT NULL ENABLE, 
	"ESCRITORIOPRINCIPAL" NUMBER(3,0), 
	"LIDER" NUMBER(9,0) NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("NUMERO") ENABLE
   ) ;
ALTER TABLE  "DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_FK" FOREIGN KEY ("LIDER") REFERENCES  "PROFESSOR" ("NRCONTRIBUINTE") ENABLE;

CREATE TABLE  "ESPECIALIDADE" 
   (	"PROFESSOR" NUMBER(9,0) NOT NULL ENABLE, 
	"ESPECIALIDADE" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "ESPECIALIDADE_PK" PRIMARY KEY ("PROFESSOR", "ESPECIALIDADE") ENABLE
   ) ;

ALTER TABLE  "ESPECIALIDADE" ADD CONSTRAINT "ESPECIALIDADE_FK" FOREIGN KEY ("PROFESSOR") REFERENCES  "PROFESSOR" ("NRCONTRIBUINTE") ENABLE;

CREATE TABLE  "PROJECTO" 
   (	"NUMERO" NUMBER(9,0) NOT NULL ENABLE, 
	"ORGFINANCIADOR" VARCHAR2(50), 
	"DATAINICIO" VARCHAR2(10) NOT NULL ENABLE, 
	"DATAFIM" VARCHAR2(10), 
	"ORCAMENTO" NUMBER(10,2), 
	"GESTOR" NUMBER(9,0) NOT NULL ENABLE, 
	 CONSTRAINT "PROJECTO_PK" PRIMARY KEY ("NUMERO") ENABLE
   ) ;
ALTER TABLE  "PROJECTO" ADD CONSTRAINT "PROJECTO_FK" FOREIGN KEY ("GESTOR") REFERENCES  "PROFESSOR" ("NRCONTRIBUINTE") ENABLE;

CREATE TABLE  "ESTUDANTE" 
   (	"NRCONTRIBUINTE" NUMBER(9,0) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"DATANASCIMENTO" VARCHAR2(10) NOT NULL ENABLE, 
	"CONSELHEIRO" NUMBER(9,0), 
	"DEPARTAMENTO" NUMBER(3,0), 
	 CONSTRAINT "ESTUDANTE_PK" PRIMARY KEY ("NRCONTRIBUINTE") ENABLE
   ) ;
ALTER TABLE  "ESTUDANTE" ADD CONSTRAINT "ESTUDANTE_CON" FOREIGN KEY ("CONSELHEIRO") REFERENCES  "ESTUDANTE" ("NRCONTRIBUINTE") ENABLE;
ALTER TABLE  "ESTUDANTE" ADD CONSTRAINT "ESTUDANTE_FK" FOREIGN KEY ("DEPARTAMENTO") REFERENCES  "DEPARTAMENTO" ("NUMERO") ENABLE;

CREATE TABLE  "TELEFONE" 
   (	"TELEFONE" NUMBER(9,0) NOT NULL ENABLE, 
	"ALUNO" NUMBER(9,0) NOT NULL ENABLE, 
	 CONSTRAINT "TELEFONE_PK" PRIMARY KEY ("TELEFONE", "ALUNO") ENABLE
   ) ;

ALTER TABLE  "TELEFONE" ADD CONSTRAINT "TELEFONE_FK" FOREIGN KEY ("ALUNO") REFERENCES  "ESTUDANTE" ("NRCONTRIBUINTE") ENABLE;

CREATE TABLE  "TRABALHADEPARTAMENTO" 
   (	"PROFESSOR" NUMBER(9,0), 
	"DEPARTAMENTO" NUMBER(3,0), 
	"PERCTEMPO" NUMBER(3,0), 
	 CONSTRAINT "TRABALHADEPARTAMENTO_PK" PRIMARY KEY ("PROFESSOR", "DEPARTAMENTO") ENABLE
   ) ;
ALTER TABLE  "TRABALHADEPARTAMENTO" ADD CONSTRAINT "TRABALHADEPARTAMENTO_FK" FOREIGN KEY ("PROFESSOR") REFERENCES  "PROFESSOR" ("NRCONTRIBUINTE") ENABLE;
ALTER TABLE  "TRABALHADEPARTAMENTO" ADD CONSTRAINT "TRABALHADEPARTAMENTO_FK2" FOREIGN KEY ("DEPARTAMENTO") REFERENCES  "DEPARTAMENTO" ("NUMERO") ENABLE;

CREATE TABLE  "ESTUDANTETRABALHA" 
   (	"ESTUDANTE" NUMBER(9,0) NOT NULL ENABLE, 
	"SUPERVISOR" NUMBER(9,0) NOT NULL ENABLE, 
	"PROJECTO" NUMBER(9,0) NOT NULL ENABLE, 
	 CONSTRAINT "ESTUDANTETRABALHA_CON" PRIMARY KEY ("ESTUDANTE", "SUPERVISOR", "PROJECTO") ENABLE
   ) ;

ALTER TABLE  "ESTUDANTETRABALHA" ADD CONSTRAINT "ESTUDANTETRABALHA_FK" FOREIGN KEY ("ESTUDANTE") REFERENCES  "ESTUDANTE" ("NRCONTRIBUINTE") ENABLE;
ALTER TABLE  "ESTUDANTETRABALHA" ADD CONSTRAINT "ESTUDANTETRABALHA_FK2" FOREIGN KEY ("SUPERVISOR") REFERENCES  "PROFESSOR" ("NRCONTRIBUINTE") ENABLE;
ALTER TABLE  "ESTUDANTETRABALHA" ADD CONSTRAINT "ESTUDANTETRABALHA_FK3" FOREIGN KEY ("PROJECTO") REFERENCES  "PROJECTO" ("NUMERO") ENABLE;

CREATE TABLE  "TRABALHAPROJECTO" 
   (	"PROFESSOR" NUMBER(9,0) NOT NULL ENABLE, 
	"PROJECTO" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "TRABALHAPROJECTO_PK" PRIMARY KEY ("PROFESSOR", "PROJECTO") ENABLE
   ) ;

ALTER TABLE  "TRABALHAPROJECTO" ADD CONSTRAINT "TRABALHAPROJECTO_FK" FOREIGN KEY ("PROFESSOR") REFERENCES  "PROFESSOR" ("NRCONTRIBUINTE") ENABLE;
ALTER TABLE  "TRABALHAPROJECTO" ADD CONSTRAINT "TRABALHAPROJECTO_FK2" FOREIGN KEY ("PROJECTO") REFERENCES  "PROJECTO" ("NUMERO") ENABLE;


